# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Automatas.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(633, 470)
        MainWindow.setMinimumSize(QtCore.QSize(633, 470))
        MainWindow.setMaximumSize(QtCore.QSize(633, 470))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.center = QtWidgets.QGroupBox(self.centralwidget)
        self.center.setGeometry(QtCore.QRect(-10, 0, 641, 471))
        self.center.setStyleSheet("background-color: rgba(22,27,34,255);")
        self.center.setTitle("")
        self.center.setObjectName("center")
        self.label_title = QtWidgets.QLabel(self.center)
        self.label_title.setGeometry(QtCore.QRect(40, 30, 541, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.Ejecute_button = QtWidgets.QPushButton(self.center)
        self.Ejecute_button.setGeometry(QtCore.QRect(260, 80, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Ejecute_button.setFont(font)
        self.Ejecute_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ejecute_button.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Ejecute_button.setAutoFillBackground(False)
        self.Ejecute_button.setStyleSheet("background-color: rgba(35,134,54,255);\n"
"color: rgb(255, 255, 255);")
        self.Ejecute_button.setAutoDefault(False)
        self.Ejecute_button.setDefault(False)
        self.Ejecute_button.setFlat(False)
        self.Ejecute_button.setObjectName("Ejecute_button")
        self.param_box = QtWidgets.QGroupBox(self.center)
        self.param_box.setGeometry(QtCore.QRect(60, 140, 241, 251))
        self.param_box.setStyleSheet("background-color: rgb(186,189,192);")
        self.param_box.setAlignment(QtCore.Qt.AlignCenter)
        self.param_box.setObjectName("param_box")
        self.random_button = QtWidgets.QRadioButton(self.param_box)
        self.random_button.setGeometry(QtCore.QRect(90, 200, 82, 17))
        self.random_button.setObjectName("random_button")
        self.button_single = QtWidgets.QRadioButton(self.param_box)
        self.button_single.setGeometry(QtCore.QRect(90, 170, 82, 17))
        self.button_single.setChecked(True)
        self.button_single.setAutoRepeat(False)
        self.button_single.setObjectName("button_single")
        self.label_pos = QtWidgets.QLabel(self.param_box)
        self.label_pos.setGeometry(QtCore.QRect(40, 140, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_pos.setFont(font)
        self.label_pos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_pos.setAutoFillBackground(False)
        self.label_pos.setObjectName("label_pos")
        self.horizontalSlider = QtWidgets.QSlider(self.param_box)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 80, 160, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.horizontalSlider.setFont(font)
        self.horizontalSlider.setMouseTracking(False)
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.horizontalSlider.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.horizontalSlider.setMaximum(2)
        self.horizontalSlider.setProperty("value", 1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(self.param_box)
        self.label.setGeometry(QtCore.QRect(20, 110, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.param_box)
        self.label_2.setGeometry(QtCore.QRect(100, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.param_box)
        self.label_3.setGeometry(QtCore.QRect(180, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_position = QtWidgets.QLabel(self.param_box)
        self.label_position.setGeometry(QtCore.QRect(30, 30, 181, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_position.setFont(font)
        self.label_position.setObjectName("label_position")
        self.rule_groupbox = QtWidgets.QGroupBox(self.center)
        self.rule_groupbox.setGeometry(QtCore.QRect(350, 140, 231, 231))
        self.rule_groupbox.setStyleSheet("background-color: rgb(186,189,192);")
        self.rule_groupbox.setObjectName("rule_groupbox")
        self.rule_label = QtWidgets.QLabel(self.rule_groupbox)
        self.rule_label.setGeometry(QtCore.QRect(10, 20, 221, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rule_label.setFont(font)
        self.rule_label.setObjectName("rule_label")
        self.rule_spinBox = QtWidgets.QSpinBox(self.rule_groupbox)
        self.rule_spinBox.setGeometry(QtCore.QRect(100, 50, 42, 22))
        self.rule_spinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rule_spinBox.setAutoFillBackground(True)
        self.rule_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.rule_spinBox.setMaximum(255)
        self.rule_spinBox.setObjectName("rule_spinBox")
        self.label_size = QtWidgets.QLabel(self.rule_groupbox)
        self.label_size.setGeometry(QtCore.QRect(10, 90, 221, 16))
        self.label_size.setObjectName("label_size")
        self.height_spinBox = QtWidgets.QSpinBox(self.rule_groupbox)
        self.height_spinBox.setGeometry(QtCore.QRect(160, 130, 51, 22))
        self.height_spinBox.setAutoFillBackground(True)
        self.height_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.height_spinBox.setMinimum(1)
        self.height_spinBox.setMaximum(2500)
        self.height_spinBox.setProperty("value", 600)
        self.height_spinBox.setObjectName("height_spinBox")
        self.label_height = QtWidgets.QLabel(self.rule_groupbox)
        self.label_height.setGeometry(QtCore.QRect(20, 130, 131, 16))
        self.label_height.setObjectName("label_height")
        self.label_large = QtWidgets.QLabel(self.rule_groupbox)
        self.label_large.setGeometry(QtCore.QRect(20, 170, 101, 16))
        self.label_large.setObjectName("label_large")
        self.large_spinBox = QtWidgets.QSpinBox(self.rule_groupbox)
        self.large_spinBox.setGeometry(QtCore.QRect(160, 170, 51, 22))
        self.large_spinBox.setAutoFillBackground(True)
        self.large_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.large_spinBox.setWrapping(False)
        self.large_spinBox.setMinimum(1)
        self.large_spinBox.setMaximum(2500)
        self.large_spinBox.setProperty("value", 800)
        self.large_spinBox.setObjectName("large_spinBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Autómatas celulares"))
        self.label_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#c1c6cc;\">Automátas celulares unidimensionales (Wolfram et. al.)</span></p></body></html>"))
        self.Ejecute_button.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.Ejecute_button.setText(_translate("MainWindow", "Ejecutar"))
        self.param_box.setTitle(_translate("MainWindow", "Parámetros iniciales"))
        self.random_button.setText(_translate("MainWindow", "Aleatorio"))
        self.button_single.setText(_translate("MainWindow", " Singular"))
        self.label_pos.setText(_translate("MainWindow", "Seleccione la formación inicial"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Izquierda</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Centro</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Derecha</p></body></html>"))
        self.label_position.setText(_translate("MainWindow", "Seleccione la posición de inicio"))
        self.rule_groupbox.setTitle(_translate("MainWindow", "Reglas y dimensiones"))
        self.rule_label.setText(_translate("MainWindow", "Seleccione la regla a realizar (0-255)"))
        self.label_size.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Seleccione las dimensiones (1-2500)</span></p></body></html>"))
        self.label_height.setText(_translate("MainWindow", "Alto (n° de generaciones)"))
        self.label_large.setText(_translate("MainWindow", "Largo (n° de casillas)"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

